
service: juanjolescano-getall-integrador

frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource: arn:aws:dynamodb:us-east-1:450865910417:table/juanjoselescano-clients

functions:
    listClient:
      handler: listClient.handler
      description: 'An API that get all clients'
      events:
        - http:
            path: clients
            method: GET

